sensor:

  - platform: rest
    name: pronote_edt_demo_aujourdhui 
    scan_interval: 10
    json_attributes:
      - edt_aujourdhui
    value_template: >
        {% if value_json.edt_aujourdhui.0 is defined %}
            {{ value_json.edt_aujourdhui.0.date_heure }}
        {% else %}
            None
        {% endif %}
    resource: http://192.168.XX.XX:8123/local/pronote_edt_demo.json
    
  - platform: rest
    name: pronote_edt_demo_demain 
    scan_interval: 10
    json_attributes:
      - edt_demain
    value_template: >
        {% if value_json.edt_demain.0 is defined %}
            {{ value_json.edt_demain.0.date_heure }}
        {% else %}
            None
        {% endif %}
    resource: http://192.168.XX.XX:8123/local/pronote_edt_demo.json
    
  - platform: rest
    name: pronote_edt_demo_prochainjour 
    scan_interval: 10
    json_attributes:
      - edt_prochainjour
    value_template: >
        {% if value_json.edt_prochainjour.0 is defined %}
            {{ value_json.edt_prochainjour.0.date_heure }}
        {% else %}
            None
        {% endif %}
    resource: http://192.168.XX.XX:8123/local/pronote_edt_demo.json


  - platform: rest
    name: pronote_note_demo
    scan_interval: 10
    json_attributes:
      - note
    value_template: >
        {% if value_json.note.0 is defined %}
            {{ value_json.note.0.cours }} : {{ value_json.note.0.note_sur }} 
        {% else %}
            None
        {% endif %}
    resource: http://192.168.10.13:8123/local/pronote_demo.json


  - platform: rest
    name: pronote_devoir_demo
    scan_interval: 10
    json_attributes:
      - devoir
    value_template: >
        {% if value_json.devoir.0 is defined %}
            {{ value_json.devoir.0.date }} / {{ value_json.devoir.0.title }} 
        {% else %}
            None
        {% endif %}
    resource: http://192.168.10.13:8123/local/pronote_demo.json